name: main workflow

on:
  - push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: date +%FT%T | tee date.txt
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: artifact
          path: date.txt
  after:
    needs: main
    uses: ${{ github.repository }}/.github/workflows/_reusable_workflow.yml@main
    with:
    secrets: inherit
